substitutions:
  device_name: powerpal-gateway
  friendly_name: Powerpal Gateway

esphome:
  name: ${device_name}
  on_boot:
    - priority: 600
      then:
        - logger.log: "Boot - LED red"
        - light.turn_off:
            id: "built_in_led"
        - delay: 500ms
        - light.turn_on:
            id: "built_in_led"
            brightness: 100%
            transition_length: 0.1s
            red: 100%
            green: 0%
            blue: 0%
    - priority: 240
      then:
        - logger.log: "Boot - LED yellow"
        - light.turn_on:
            id: "built_in_led"
            brightness: 50%
            transition_length: 0.1s
            red: 100%
            green: 100%
            blue: 0%
        - wait_until:
            api.connected:
        - logger.log: "Boot - LED green"
        - light.turn_on:
            id: "built_in_led"
            brightness: 50%
            transition_length: 0.1s
            red: 0%
            green: 100%
            blue: 0%
        - delay: 60s
        - light.turn_off:
            id: "built_in_led"
  platformio_options:
    upload_speed: 115200

esp32:
  board: m5stack-core-esp32
  framework:
    type: arduino

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:

api:
  encryption:
    key: !secret powerpal_gateway_esphome_encryption_key

ota:
  - platform: esphome
    password: !secret esphome_ota_password

external_components:
  - source:
     type: git
     url: https://github.com/muneeb1990/esphome
     ref: powerpal_ble
    components: [ powerpal_ble ]

# esp32_ble_tracker:

ble_client:
  - mac_address: !secret powerpal_mac_address
    id: powerpal

time:
  - platform: homeassistant
    id: homeassistant_time

# http_request:
#   id: powerpal_cloud_uploader

sensor:
  - platform: powerpal_ble
    ble_client_id: powerpal
    power:
      name: "Powerpal Power"
      accuracy_decimals: 0
    energy:
      name: "Powerpal Total Energy"
      accuracy_decimals: 3
    daily_energy:
      name: "Powerpal Daily Energy"
      accuracy_decimals: 0
    battery_level:
      name: "Powerpal Battery"
    pairing_code: !secret powerpal_pairing_code
    notification_interval: 1 # get updates every 1 minute
    pulses_per_kwh: 3200
    time_id: homeassistant_time
    cost_per_kwh: 0.29 #dollars per kWh

light:
  - platform: fastled_clockless
    chipset: SK6812
    pin: 27
    num_leds: 1
    rgb_order: GRB
    name: "Built-In LED"
    id: built_in_led